### ISSUE TITLE
Using TYPO3-404 handling

### ISSUE THREAD

**Issue by meincms** [TYPO3-Initiatives/nuxt-typo3#19]
Is there any way to use the TYPO3 Error-Handling? 

i.E. when configuring the 404-Error-Handling in TYPO3 and the site cannot be found, the website renders the 404-content, but sends an additional 404-Header. What's your recommendation to handle Errors? In fact it leads to the nuxtjs-typo3-error site – and doesn't render the intended content of the errorHandling-site of the TYPO3.... 

```
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=30'
```
